use_frameworks!

platform :ios, '9.0'

target 'HXCategories_Example' do
  pod 'HXCategories', :path => '../'

  target 'HXCategories_Tests' do
    inherit! :search_paths

    # pod 'FBSnapshotTestCase'
  end
end
